const datas = [
    {
      name: "Red shirt",
      color:['black','blue','red','yellow','grey','white','brown'],
      size:['sm','md','lg','xl'],
      actualPrice: 100,
      discPrice: 10,
      image: "/images/1.jpeg",
      category: "men",
      countInStock: 20,
      description: " recreate your fashion sense by wearing these pair of black coloured denims from bulk. featuring washed effect and classic 5 pocket styling that comes together with a perfect slim fit pattern that gives them a sharp look. the cotton spandex fabric of these jeans promises great stretchability and comfort all day long. team  them best with a contrast printed t-shirt, sneakers and a jacket.",
      slug: "red-shirt",
      id: 1,
    },
    {
      name: "Rwandan T-shirt",
      color:['black','blue','red','yellow','grey','white','brown'],
      size:['sm','md','lg','xl'],
      actualPrice: 100,
      discPrice: 10,
      image: "/images/2.jpeg",
      category: "women",
      countInStock: 20,
      description: " recreate your fashion sense by wearing these pair of black coloured denims from bulk. featuring washed effect and classic 5 pocket styling that comes together with a perfect slim fit pattern that gives them a sharp look. the cotton spandex fabric of these jeans promises great stretchability and comfort all day long. team  them best with a contrast printed t-shirt, sneakers and a jacket.",
      slug: "redrwanda-shirt",
      id: 2,
    },
    {
      name: "White Tshirt",
      color:['black','blue','red','yellow','grey','white','brown'],
      size:['sm','md','lg','xl'],
      actualPrice: 100,
      discPrice: 10,
      image: "/images/4.jpeg",
      category: "men",
      countInStock: 20,
      description: " recreate your fashion sense by wearing these pair of black coloured denims from bulk. featuring washed effect and classic 5 pocket styling that comes together with a perfect slim fit pattern that gives them a sharp look. the cotton spandex fabric of these jeans promises great stretchability and comfort all day long. team  them best with a contrast printed t-shirt, sneakers and a jacket.",
      slug: "red-tshirt",
      id: 3,
    },
    {
      name: "Blue shirt",
      color:['black','blue','red','yellow','grey','white','brown'],
      size:['sm','md','lg','xl'],
      actualPrice: 100,
      discPrice: 10,
      image: "/images/6.jpeg",
      category: "men",
      countInStock: 20,
      description: " recreate your fashion sense by wearing these pair of black coloured denims from bulk. featuring washed effect and classic 5 pocket styling that comes together with a perfect slim fit pattern that gives them a sharp look. the cotton spandex fabric of these jeans promises great stretchability and comfort all day long. team  them best with a contrast printed t-shirt, sneakers and a jacket.",
      slug: "blue-shirt1",
      id: 4,
    },
    {
      name: "Rwandan short",
      color:['black','blue','red','yellow','grey','white','brown'],
      size:['sm','md','lg','xl'],
      actualPrice: 0,
      discPrice: 10,
      image: "/images/3.jpeg",
      category: "women",
      countInStock: 20,
      description: " recreate your fashion sense by wearing these pair of black coloured denims from bulk. featuring washed effect and classic 5 pocket styling that comes together with a perfect slim fit pattern that gives them a sharp look. the cotton spandex fabric of these jeans promises great stretchability and comfort all day long. team  them best with a contrast printed t-shirt, sneakers and a jacket.",
      slug: "rwanda-short",
      id: 5,
    },
    {
      name: "Blue short",
      color:['black','blue','red','yellow','grey','white','brown'],
      size:['sm','md','lg','xl'],
      actualPrice: 100,
      discPrice: 10,
      image: "/images/5.jpeg",
      category: "women",
      countInStock: 20,
      description: " recreate your fashion sense by wearing these pair of black coloured denims from bulk. featuring washed effect and classic 5 pocket styling that comes together with a perfect slim fit pattern that gives them a sharp look. the cotton spandex fabric of these jeans promises great stretchability and comfort all day long. team  them best with a contrast printed t-shirt, sneakers and a jacket.",
      slug: "blue-shirt",
      id: 6,
    },
    {
      name: "Black shirt",
      color:['black','blue','red','yellow','grey','white','brown'],
      size:['sm','md','lg','xl'],
      actualPrice: 100,
      discPrice: 10,
      image: "/images/men8.jpg",
      category: "men",
      countInStock: 20,
      description: " recreate your fashion sense by wearing these pair of black coloured denims from bulk. featuring washed effect and classic 5 pocket styling that comes together with a perfect slim fit pattern that gives them a sharp look. the cotton spandex fabric of these jeans promises great stretchability and comfort all day long. team  them best with a contrast printed t-shirt, sneakers and a jacket.",
      slug: "black-shirt",
      id: 7,
    },
    {
      name: "sandals shoes",
      color:['black','blue','red','yellow','grey','white','brown'],
      size:['sm','md','lg','xl'],
      actualPrice: 100,
      discPrice: 10,
      image: "/images/sandal4.jpg",
      category: "sandals",
      countInStock: 20,
      description: " recreate your fashion sense by wearing these pair of black coloured denims from bulk. featuring washed effect and classic 5 pocket styling that comes together with a perfect slim fit pattern that gives them a sharp look. the cotton spandex fabric of these jeans promises great stretchability and comfort all day long. team  them best with a contrast printed t-shirt, sneakers and a jacket.",
      slug: "sandals-shoes",
      id: 8,
    },
    {
      name: "White shirt",
      color:['black','blue','red','yellow','grey','white','brown'],
      size:['sm','md','lg','xl'],
      actualPrice: 100,
      discPrice: 10,
      image: "/images/6.jpeg",
      category: "men",
      countInStock: 20,
      description: " recreate your fashion sense by wearing these pair of black coloured denims from bulk. featuring washed effect and classic 5 pocket styling that comes together with a perfect slim fit pattern that gives them a sharp look. the cotton spandex fabric of these jeans promises great stretchability and comfort all day long. team  them best with a contrast printed t-shirt, sneakers and a jacket.",
      slug: "white-shirt",
      id: 9,
    },
    {
      name: "Long sleeve shirt",
      color:['black','blue','red','yellow','grey','white','brown'],
      size:['sm','md','lg','xl'],
      actualPrice: 100,
      discPrice: 10,
      image: "/images/men6.jpg",
      category: "men",
      countInStock: 20,
      description: " recreate your fashion sense by wearing these pair of black coloured denims from bulk. featuring washed effect and classic 5 pocket styling that comes together with a perfect slim fit pattern that gives them a sharp look. the cotton spandex fabric of these jeans promises great stretchability and comfort all day long. team  them best with a contrast printed t-shirt, sneakers and a jacket.",
      slug: "long-shirt",
      id: 10,
    },
    {
      name: "Black collection",
      color:['black','blue','red','yellow','grey','white','brown'],
      size:['sm','md','lg','xl'],
      actualPrice: 100,
      discPrice: 10,
      image: "/images/10.jpg",
      category: "men",
      countInStock: 20,
      description: " recreate your fashion sense by wearing these pair of black coloured denims from bulk. featuring washed effect and classic 5 pocket styling that comes together with a perfect slim fit pattern that gives them a sharp look. the cotton spandex fabric of these jeans promises great stretchability and comfort all day long. team  them best with a contrast printed t-shirt, sneakers and a jacket.",
      slug: "black-shirt2",
      id: 11,
    },
    {
      name: "Yellow Short",
      color:['black','blue','red','yellow','grey','white','brown'],
      size:['sm','md','lg','xl'],
      actualPrice: 100,
      discPrice: 10,
      image: "/images/7.jpeg",
      category: "women",
      countInStock: 20,
      description: " recreate your fashion sense by wearing these pair of black coloured denims from bulk. featuring washed effect and classic 5 pocket styling that comes together with a perfect slim fit pattern that gives them a sharp look. the cotton spandex fabric of these jeans promises great stretchability and comfort all day long. team  them best with a contrast printed t-shirt, sneakers and a jacket.",
      slug: "yellow-shirt",
      id: 12,
    },
    {
      name: "Umuzingo Short",
      color:['black','blue','red','yellow','grey','white','brown'],
      size:['sm','md','lg','xl'],
      actualPrice: 100,
      discPrice: 10,
      image: "/images/9.jpeg",
      category: "women",
      countInStock: 20,
      description: " recreate your fashion sense by wearing these pair of black coloured denims from bulk. featuring washed effect and classic 5 pocket styling that comes together with a perfect slim fit pattern that gives them a sharp look. the cotton spandex fabric of these jeans promises great stretchability and comfort all day long. team  them best with a contrast printed t-shirt, sneakers and a jacket.",
      slug: "umuzingo-short",
      id: 13,
    },
    {
      name: "Casual",
      color:['black','blue','red','yellow','grey','white','brown'],
      size:['sm','md','lg','xl'],
      actualPrice: 100,
      discPrice: 10,
      image: "/images/dress3.jpg",
      category: "women",
      countInStock: 20,
      description: " recreate your fashion sense by wearing these pair of black coloured denims from bulk. featuring washed effect and classic 5 pocket styling that comes together with a perfect slim fit pattern that gives them a sharp look. the cotton spandex fabric of these jeans promises great stretchability and comfort all day long. team  them best with a contrast printed t-shirt, sneakers and a jacket.",
      slug: "casual",
      id: 14,
    },
    {
      name: "Red long Tshirt",
      color:['black','blue','red','yellow','grey','white','brown'],
      size:['sm','md','lg','xl'],
      actualPrice: 100,
      discPrice: 10,
      image: "/images/dress5.jpg",
      category: "women",
      countInStock: 20,
      description: " recreate your fashion sense by wearing these pair of black coloured denims from bulk. featuring washed effect and classic 5 pocket styling that comes together with a perfect slim fit pattern that gives them a sharp look. the cotton spandex fabric of these jeans promises great stretchability and comfort all day long. team  them best with a contrast printed t-shirt, sneakers and a jacket.",
      slug: "red-long-shirt2",
      id: 15,
    },
    {
      name: "Long shirt",
      color:['black','blue','red','yellow','grey','white','brown'],
      size:['sm','md','lg','xl'],
      actualPrice: 100,
      discPrice: 10,
      image: "/images/dress2.jpg",
      category: "women",
      countInStock: 20,
      description: " recreate your fashion sense by wearing these pair of black coloured denims from bulk. featuring washed effect and classic 5 pocket styling that comes together with a perfect slim fit pattern that gives them a sharp look. the cotton spandex fabric of these jeans promises great stretchability and comfort all day long. team  them best with a contrast printed t-shirt, sneakers and a jacket.",
      slug: "long-shirt2",
      id: 16,
    },
    {
      name: "many shoes",
      color:['black','blue','red','yellow','grey','white','brown'],
      size:['sm','md','lg','xl'],
      actualPrice: 100,
      discPrice: 10,
      image: "/images/sandal2.jpg",
      category: "sandals",
      countInStock: 20,
      description: " recreate your fashion sense by wearing these pair of black coloured denims from bulk. featuring washed effect and classic 5 pocket styling that comes together with a perfect slim fit pattern that gives them a sharp look. the cotton spandex fabric of these jeans promises great stretchability and comfort all day long. team  them best with a contrast printed t-shirt, sneakers and a jacket.",
      slug: "many-shoes",
      id: 17,
    },
    {
      name: "shoe",
      color:['black','blue','red','yellow','grey','white','brown'],
      size:['sm','md','lg','xl'],
      actualPrice: 100,
      discPrice: 10,
      image: "/images/sandal1.jpg",
      category: "sandals",
      countInStock: 20,
      description: " recreate your fashion sense by wearing these pair of black coloured denims from bulk. featuring washed effect and classic 5 pocket styling that comes together with a perfect slim fit pattern that gives them a sharp look. the cotton spandex fabric of these jeans promises great stretchability and comfort all day long. team  them best with a contrast printed t-shirt, sneakers and a jacket.",
      slug: "shoe",
      id: 18,
    },
    {
      name: "shoe black",
      color:['black','blue','red','yellow','grey','white','brown'],
      size:['sm','md','lg','xl'],
      actualPrice: 100,
      discPrice: 10,
      image: "/images/sandal.jpg",
      category: "sandals",
      countInStock: 20,
      description: " recreate your fashion sense by wearing these pair of black coloured denims from bulk. featuring washed effect and classic 5 pocket styling that comes together with a perfect slim fit pattern that gives them a sharp look. the cotton spandex fabric of these jeans promises great stretchability and comfort all day long. team  them best with a contrast printed t-shirt, sneakers and a jacket.",
      slug: "shoe-black",
      id: 19,
    },
    {
      name: "shirt",
      color:['black','blue','red','yellow','grey','white','brown'],
      size:['sm','md','lg','xl'],
      actualPrice: 100,
      discPrice: 10,
      image: "/images/kids.jpg",
      category: "kids",
      countInStock: 20,
      description: " recreate your fashion sense by wearing these pair of black coloured denims from bulk. featuring washed effect and classic 5 pocket styling that comes together with a perfect slim fit pattern that gives them a sharp look. the cotton spandex fabric of these jeans promises great stretchability and comfort all day long. team  them best with a contrast printed t-shirt, sneakers and a jacket.",
      slug: "shoe-kids",
      id: 19,
    },
  ]
export default datas
